name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


env:
  PREFIX: /opt
  TARGET: tricore
  CC: gcc-9 
  CXX: g++-9 
  CFLAGS: -w

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -yy \
         bison \
         bzip2 \
         ca-certificates \
         ccache \
         flex \
         g++-9 \
         gcc-9 \
         git \
         libglib2.0-dev \
         libpixman-1-dev \
         libgmp-dev \
         libmpfr-dev \
         libmpc-dev \
         locales \
         make \
         ninja-build \
         pkgconf \
         python3-pip \
         python3-setuptools \
         python3-wheel \
         texinfo

    - name: configure
      run: |
        mkdir ${{env.PREFIX}}
        ./configure --prefix=${{env.PREFIX}} --target=${{env.TARGET}} --enable-lto --with-sysroot --disable-nls --disable-werror

    - name: build
      run: make -j 10
      
    - name: install
      run: make install
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: file_system
        path: /opt
    
