name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


env:
  PREFIX: /opt/tricore
  TARGET: tricore
  CC: gcc-9 
  CXX: g++-9 
  CFLAGS: -w

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt update && sudo apt install -yy g++-9 gcc-9 git flex bison texinfo make 

    - name: configure
      run: |
        mkdir -p ${{env.PREFIX}}
        ./configure --prefix=$PREFIX --target=${{env.TARGET}} --enable-lto --with-sysroot --disable-nls --disable-werror

    - name: build
      run: make -j 10
      
    - name: install
      run: make install
      
    - name: tar files
      run: tar -cvf file_system.tar ${{env.PREFIX}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: file_system
        path: file_system.tar
    
